# this profile is meant to be used on NERSC login nodes

configfile: simflow-config.yaml
rerun-incomplete: true

local-storage-prefix: $SCRATCH/legend-simflow
shared-fs-usage: [persistence, software-deployment, sources, source-cache]

# there are caps on resources on login nodes:
# https://docs.nersc.gov/policies/resource-usage/#usage-limits
cores: 10
resources:
  mem_mb: 56000
