configfile: simflow-config.yaml
keep-going: true
rerun-incomplete: true
cores: all

# I/O on scratch disk for performance
default-storage-provider: fs
# "local" refers to the scratch disk
local-storage-prefix: $SCRATCH/legend-simflow
# while the "remote" or "shared" storage is the CFS
shared-fs-usage:
  - persistence
  - software-deployment
  - sources
  - source-cache
